#!/usr/bin/env bash
# Deploy the public base into $HOME, then run each overlay's own link script.
# ~/.bashrc and ~/.bash_profile are REAL files that *source* the repo, so a reset
# of ~/.bashrc can't corrupt the repo; everything else is a symlink.  Idempotent:
# backs up pre-existing real files, replaces stale symlinks.  After a full deploy,
# a symlink still dangling into the dotfiles tree is a bug and is reported.
set -eu
PUB="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OVERLAYS="$(dirname "$PUB")/dotfiles-overlays"
export GCLOCAL="$HOME/.gitconfig.local"
export DOTFILES_LINK_LIB="$PUB/link-lib.sh"
. "$DOTFILES_LINK_LIB"

# --- base files (generic; usable on their own) ---
realsource "$HOME/.bashrc"       "$PUB/bash/bashrc"
realsource "$HOME/.bash_profile" "$PUB/bash/bash_profile"
link "$PUB/emacs/emacsrc"        "$HOME/.emacs"
link "$PUB/emacs/gnusrc"         "$HOME/.gnus"
link "$PUB/tmux/tmux.conf"       "$HOME/.tmux.conf"
link "$PUB/ssh/config"           "$HOME/.ssh/config"
link "$PUB/dircolors/dir_colors" "$HOME/.dir_colors"
link "$PUB/screen/screenrc"      "$HOME/.screenrc"
link "$PUB/terminfo"             "$HOME/.terminfo"

# --- overlays: start a fresh git include list, then run each overlay's link.sh
# in the order install.sh recorded in .order (later overlays win), falling back
# to a sorted glob.  The base itself names no specific overlay. ---
printf '# generated by link.sh from the cloned overlays\n[include]\n' > "$GCLOCAL"
if [ -r "$OVERLAYS/.order" ]; then
  mapfile -t overlay_order < <(grep -vE '^[[:space:]]*(#|$)' "$OVERLAYS/.order")
else
  mapfile -t overlay_order < <(cd "$OVERLAYS" 2>/dev/null && for d in */; do [ -d "$d" ] && printf '%s\n' "${d%/}"; done | sort)
fi
for name in "${overlay_order[@]:-}"; do
  [ -n "$name" ] || continue
  ov="$OVERLAYS/$name"
  if [ -r "$ov/link.sh" ]; then echo ">> linking overlay $name"; bash "$ov/link.sh"; fi
done

# --- verify: after a full deploy nothing should dangle into the dotfiles tree ---
bad=0
while IFS= read -r l; do
  t="$(readlink "$l")"
  case "$t" in
    "$PUB"/*|"$OVERLAYS"/*)
      if [ ! -e "$l" ]; then echo "!! STALE LINK (bug): $l -> $t" >&2; bad=$((bad + 1)); fi ;;
  esac
done < <(find "$HOME" -maxdepth 2 -type l 2>/dev/null)
if [ "$bad" -ne 0 ]; then
  echo "!! $bad stale link(s) into the dotfiles tree — an overlay link script is missing coverage" >&2
else
  echo "linked \$HOME -> dotfiles (base + overlays, no stale links)"
fi
